services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped
    # Aguarda o banco estar pronto antes de iniciar o Flask
    command: ["./wait-for-it.sh", "db:3306", "--timeout=60", "--", "python", "app.py"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: academia
      MYSQL_USER: academia_user
      MYSQL_PASSWORD: academia_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
